f = open('output.txt', 'a+')
content1 = input(("Enter text to write to the file: "))
wf1 = f.write(content1 + '\n')
print("Data successfully written to output.txt")
print()
content2 = input("Enter more text to write to the file: ")
wf2 = f.write(content2 + '\n')
print("Data successfully appended.")
print()
print("Final content of output.txt:")
f.seek(0)
rf = f.read()
print(rf)
f.close()
